### ISSUE TITLE
scan is broken

### ISSUE THREAD

**Issue by Krysher** [vesche/basicRAT#14]
Probably have to do with encryption

[1] basicRAT> scan 10.210.1.189
Running scan...

[1] REI> Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\Lib\threading.py", line 530, in __bootstrap_inner
    self.run()
  File "C:\Users\someone\Desktop\rei_Rat\basicRAT_server.py", line 75, in run
    client = ClientConnection(conn, addr, uid=client_id)
  File "C:\Users\someone\Desktop\rei_Rat\core\common.py", line 19, in __init__
    self.dh_key = crypto.diffiehellman(self.conn)
  File "C:\Users\someone\Desktop\rei_Rat\core\crypto.py", line 43, in diffiehellman
    b = bytes_to_long(sock.recv(256))
error: [Errno 10053] An established connection was aborted by the software in your host machine

**Comment by deadPix3l** [comment]
Is this a persistent problem? has it happened multiple times? Its working on the master branch for us. did you change anything?

**Comment by vesche** [comment]
Closing this issue as it is not an issue with the current master branch. Looks like your own edits to the project produced this error.
