### ISSUE TITLE
getting error while running server

### ISSUE THREAD

**Issue by vikash3214** [vesche/basicRAT#26]
Traceback (most recent call last):
  File "C:\Users\vikash\Desktop\New folder (2)\basicRAT-master\basicRAT_server.py", line 224, in <module>
    main()
  File "C:\Users\vikash\Desktop\New folder (2)\basicRAT-master\basicRAT_server.py", line 176, in main
    server = Server(port)
  File "C:\Users\vikash\Desktop\New folder (2)\basicRAT-master\basicRAT_server.py", line 61, in __init__
    self.s.bind(('0.0.0.0', 1337))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions

**Comment by vesche** [comment]
Run it with a higher privilege level.
