### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by edenanthony** [vesche/basicRAT#28]
When run basicrat_client.py on windows os powershell return back this error:

Traceback (most recent call last):
  File "C:\Users\anthony\Downloads\basicRAT-master\basicRAT-master\basicRAT_client.py", line 12, in <module>
    from core import *
  File "C:\Users\anthony\Downloads\basicRAT-master\basicRAT-master\core\crypto.py", line 8, in <module>
    from Crypto import Random
ImportError: No module named Crypto

How to solve it? TNX

**Comment by vesche** [comment]
http://www.voidspace.org.uk/python/modules.shtml#pycrypto
