### ISSUE TITLE
Issue with Crypto library

### ISSUE THREAD

**Issue by NET-OF-BEING** [vesche/basicRAT#34]
I have had this same issue with importing Random from Crypto Module with "Stitch".

 File "basicRAT_client.py", line 15, in <module>
    from core import crypto, persistence, scan, survey, toolkit
  File "/Users/derekchan/GitHub/basicRAT/basicRAT/core/crypto.py", line 10, in <module>
    from Crypto import Random
ImportError: No module named Crypto

What do I need to do to fix this?

**Comment by vesche** [comment]
Make sure you are using Python 3 and have either the PyCrypto or PyCryptodome library installed.

For example my system looks like this:
```
$ python --version
Python 3.6.4
$ pip freeze | grep -i crypto
pycrypto==2.6.1
pycryptodome==3.6.1
```

If you don't have one of the libraries, just install using pip:
```
pip3 install PyCryptodome
```

**Comment by NET-OF-BEING** [comment]
derekchan@PandaMacPro:~/GitHub/basicRAT/basicRAT$ python basicRAT_client.py 
Traceback (most recent call last):
  File "basicRAT_client.py", line 15, in <module>
    from core import crypto, persistence, scan, survey, toolkit
  File "/Users/derekchan/GitHub/basicRAT/basicRAT/core/crypto.py", line 10, in <module>
    from Crypto import Random
ImportError: No module named Crypto
derekchan@PandaMacPro:~/GitHub/basicRAT/basicRAT$ pip freeze | grep -i crypto
crypto==1.4.1
pycrypto==2.6.1
pycryptodome==3.6.1

I have the pycrypto library now but still doesnt work. Is it conflicting with the crypto library?

**Comment by vesche** [comment]
@NET-OF-BEING No, it's not a conflict problem. It's not finding the library at all `ImportError: No module named Crypto`.

Does your python version and pip version match?
```
$ python --version
Python 3.6.4
$ pip --version  
pip 9.0.1 from /usr/lib/python3.6/site-packages (python 3.6)
```

**Comment by NET-OF-BEING** [comment]
did all of that and still got this

python basicRAT_client.py 
Traceback (most recent call last):
  File "basicRAT_client.py", line 15, in <module>
    from core import crypto, persistence, scan, survey, toolkit
  File "/Users/derekchan/GitHub/basicRAT/basicRAT/core/crypto.py", line 11, in <module>
    from Crypto import Random
ImportError: No module named Crypto

**Comment by NET-OF-BEING** [comment]
pip freeze | grep -i crypto
pycrypto==2.6.1
pycryptodome==3.6.1

**Comment by vesche** [comment]
@NET-OF-BEING `$ python3 basicRAT_client.py` ...?

**Comment by NET-OF-BEING** [comment]
nope

python3 basicRAT_client.py 
Traceback (most recent call last):
  File "basicRAT_client.py", line 15, in <module>
    from core import crypto, persistence, scan, survey, toolkit
  File "/Users/derekchan/GitHub/basicRAT/basicRAT/core/crypto.py", line 11, in <module>
    from Crypto import Random
ModuleNotFoundError: No module named 'Crypto'

**Comment by vesche** [comment]
What's the output of these commands:

Try this:
```
$ pip3 install --upgrade pycrypto
```
or maybe this?
```
$ python3 -m pip install pycrypto
```
And then try `python3 basicRAT_client.py` again.

If that doesn't work what is the output of all this:
```
$ python3 -c "import sys; print(sys.path)"
$ echo $PYTHONPATH
$  ls /usr/local/lib/python3.6/site-packages
```

**Comment by NET-OF-BEING** [comment]
output of python3 -m pip install pycrypto is:

python3 -m pip install pycrypto
Requirement already satisfied: pycrypto in /usr/local/lib/python3.6/site-packages (2.6.1)
aquests 0.7.15.7 has requirement protobuf==3.1.0.post1, but you'll have protobuf 3.5.2.post1 which is incompatible.

**Comment by NET-OF-BEING** [comment]
python3 -c "import sys; print(sys.path)"
['', '/usr/loca/lib/python3.6', '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python36.zip', '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6', '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/site-packages/bitcoin_python-0.3-py3.6.egg']
derekchan@PandaMacPro:~/GitHub/basicRAT/basicRAT$ echo $PYTHONPATH
/usr/loca/lib/python3.6
derekchan@PandaMacPro:~/GitHub/basicRAT/basicRAT$ ls /usr/local/lib/python3.6/site-packages
EasyProcess-0.2.3.dist-info              event_bus-1.0.2.dist-info                jaraco.stream-1.1.2-py3.6-nspkg.pth      pyttsx3-2.7.dist-info
Eliza-1.0.0.dist-info                    external                                 jaraco.stream-1.1.2.dist-info            pytz
Markdown-2.6.11.dist-info                gTTS-1.2.2-py3.6.egg-info                jaraco.text-1.10-py3.6-nspkg.pth         pytz-2018.3.dist-info
Naked                                    gTTS_token-1.1.1-py3.6.egg-info          jaraco.text-1.10.dist-info               pyunpack
Naked-0.1.31.dist-info                   gast                                     joblib                                   pyunpack-0.1.2.dist-info
PIL                                      gast-0.2.0.dist-info                     joblib-0.11.dist-info                    redis
Pillow-5.0.0.dist-info                   google                                   librosa                                  redis-2.10.0.dist-info
PyAudio-0.2.11.dist-info                 gridfs                                   librosa-0.6.0.dist-info                  requests
PyYAML-3.11.dist-info                    grpc                                     llvmlite                                 requests-2.9.1.dist-info
SpeechRecognition-3.8.1.dist-info        grpcio-1.11.0.dist-info                  llvmlite-0.22.0.dist-info                resampy
Werkzeug-0.14.1.dist-info                gtts                                     markdown                                 resampy-0.2.0.dist-info
__pycache__                              gtts_token                               mongoengine                              retry
_portaudio.cpython-36m-darwin.so         h2                                       mongoengine-0.15.0.dist-info             retry-0.9.2.dist-info
absl                                     h2-3.0.1.dist-info                       more_itertools                           scikit_learn-0.19.1.dist-info
absl_py-0.1.13.dist-info                 hack_exe                                 more_itertools-4.1.0.dist-info           scipy
aquests                                  hack_exe-0.2.dist-info                   numba                                    scipy-1.0.0.dist-info
aquests-0.7.15.7.dist-info               hpack                                    numba-0.37.0.dist-info                   setuptools
astor                                    hpack-3.0.0.dist-info                    numpy                                    setuptools-39.0.1-py3.6.egg-info
astor-0.6.2.dist-info                    html2text                                numpy-1.14.1.dist-info                   setuputils.py
audioread                                html2text-2018.1.9.dist-info             numpy-1.14.2-py3.6.egg-info              shellescape
audioread-2.1.5.dist-info                html5lib                                 pip                                      shellescape-3.4.1.dist-info
bash                                     html5lib-0.9999999.dist-info             pip-10.0.1.dist-info                     sitecustomize.py
bash-0.6.dist-info                       hvac                                     pkg_resources                            six-1.11.0.dist-info
bitcoin_python-0.3-py3.6.egg             hvac-0.2.14.dist-info                    protobuf-3.5.2.post1-py3.6-nspkg.pth     six.py
bleach                                   hyperframe                               protobuf-3.5.2.post1.dist-info           sklearn
bleach-1.5.0.dist-info                   hyperframe-5.1.0.dist-info               psycopg2                                 sklearn-0.0.dist-info
bson                                     inflect-0.2.5.dist-info                  psycopg2-2.7.3.1.dist-info               speech_recognition
clip_the_gym-0.0.2.dist-info             inflect.py                               py                                       tempora
clipthegym                               irc                                      py-1.5.3.dist-info                       tempora-1.10.dist-info
crypto                                   irc-16.2.1.dist-info                     pyaudio.py                               tensorboard
cv2.cpython-36m-darwin.so                jaraco                                   pycrypto-2.6.1.dist-info                 tensorboard-1.7.0.dist-info
decorator-4.2.1.dist-info                jaraco.classes-1.4.3-py3.6-nspkg.pth     pycryptodome-3.6.1.dist-info             tensorflow
decorator.py                             jaraco.classes-1.4.3.dist-info           pymongo                                  tensorflow-1.7.0.dist-info
dnn                                      jaraco.collections-1.5.3-py3.6-nspkg.pth pymongo-3.4.0.dist-info                  termcolor-1.1.0.dist-info
dnn-0.1b18.dist-info                     jaraco.collections-1.5.3.dist-info       pyspeech                                 termcolor.py
easy-install.pth                         jaraco.functools-1.17-py3.6-nspkg.pth    pyspeech-0.0.0.dist-info                 vlc.py
easy_install.py                          jaraco.functools-1.17.dist-info          python_vlc-3.0.102.dist-info             werkzeug
easyprocess                              jaraco.itertools-2.1.1-py3.6-nspkg.pth   pyttsx                                   wheel
eliza                                    jaraco.itertools-2.1.1.dist-info         pyttsx-1.2-py3.6.egg-info                wheel-0.31.0.dist-info
event_bus                                jaraco.logging-1.5.1.dist-info           pyttsx3                                  yaml

**Comment by vesche** [comment]
Did you paste this wrong? Or is that really the output o.o
```
$ echo $PYTHONPATH
/usr/loca/lib/python3.6
```

**Comment by NET-OF-BEING** [comment]
echo $PYTHONPATH
/usr/loca/lib/python3.6

**Comment by vesche** [comment]
Well, that's wrong to say the least lol. Try this?
```
$ PYTHONPATH='/usr/local/lib/python3.6/site-packages'
$ python3 basicRAT_client.py
```

**Comment by NET-OF-BEING** [comment]
ok... I do understand that PYTHONPATH should be referencing the location of the packages. Not sure how it got changed...

**Comment by vesche** [comment]
Did that work? If not maybe try removing it all together and reinstalling?
```
$ rm -rf /usr/local/lib/python3.6/site-packages/pycrypto-2.6.1.dist-info
$ pip3 install pycrypto
```

**Comment by NET-OF-BEING** [comment]
when i close the terminal and reopen it the PYTHONPATH reverts back to the wrong path

**Comment by vesche** [comment]
Yeah you should add `PYTHONPATH='/usr/local/lib/python3.6/site-packages'` to your `~/.bash_profile` as well.

**Comment by NET-OF-BEING** [comment]
shouldn't python automatically know this in some config file?

**Comment by vesche** [comment]
Google says, it should be sys.path[0]. [info here](https://docs.python.org/3/library/sys.html#sys.path)

Which you said earlier is:
```
$ python3 -c "import sys; print(sys.path)"
['', '/usr/loca/lib/python3.6', '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python36.zip', '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6', '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/site-packages/bitcoin_python-0.3-py3.6.egg']`
```

But lol... /usr/loca/ is not /usr/local
Sounds like you have deployment issues. I might even reinstall Python 3 all together.
Brew is the best way to do it - https://brew.sh/
`brew install python3`

**Comment by NET-OF-BEING** [comment]
rm -rf /usr/local/lib/python3.6/site-packages/pycrypto-2.6.1.dist-info
rm: /usr/local/lib/python3.6/site-packages/pycrypto-2.6.1.dist-info/RECORD: Permission denied
rm: /usr/local/lib/python3.6/site-packages/pycrypto-2.6.1.dist-info/WHEEL: Permission denied
rm: /usr/local/lib/python3.6/site-packages/pycrypto-2.6.1.dist-info/top_level.txt: Permission denied
rm: /usr/local/lib/python3.6/site-packages/pycrypto-2.6.1.dist-info/INSTALLER: Permission denied
rm: /usr/local/lib/python3.6/site-packages/pycrypto-2.6.1.dist-info/METADATA: Permission denied
rm: /usr/local/lib/python3.6/site-packages/pycrypto-2.6.1.dist-info: Directory not empty

**Comment by vesche** [comment]
sudo that shit.

**Comment by NET-OF-BEING** [comment]
dam right!

**Comment by NET-OF-BEING** [comment]
pip3 install pycrypto

Collecting pycrypto
aquests 0.7.15.7 has requirement protobuf==3.1.0.post1, but you'll have protobuf 3.5.2.post1 which is incompatible.
Installing collected packages: pycrypto
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/site-packages/Crypto/pct_warnings.py'
Consider using the `--user` option or check the permissions.

**Comment by vesche** [comment]
`sudo pip3 install pycrypto` ?

**Comment by NET-OF-BEING** [comment]
lol

**Comment by NET-OF-BEING** [comment]
python3 basicRAT_client.py 
Traceback (most recent call last):
  File "basicRAT_client.py", line 15, in <module>
    from core import crypto, persistence, scan, survey, toolkit
  File "/Users/derekchan/GitHub/basicRAT/basicRAT/core/crypto.py", line 11, in <module>
    from Crypto import Random
ModuleNotFoundError: No module named 'Crypto'

**Comment by NET-OF-BEING** [comment]
still no go

**Comment by vesche** [comment]
I think something is seriously wrong with your Python 3 deployment. It is looking for libraries in places with incorrect paths. Uninstall python 3.

Reinstall using brew - https://brew.sh/
```
$ brew install python3
$ sudo pip3 install pycrypto
$ python3 basicRAT_client.py
```

Sorry you're having problems man.

**Comment by vesche** [comment]
Actually, before you do that for kicks what happens when you:
`sudo python3 basicRAT_client.py`

**Comment by NET-OF-BEING** [comment]
sudo pip3 install pycrypto
Password:
The directory '/Users/derekchan/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/derekchan/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: pycrypto in /usr/local/lib/python3.6/site-packages (2.6.1)
aquests 0.7.15.7 has requirement protobuf==3.1.0.post1, but you'll have protobuf 3.5.2.post1 which is incompatible.

**Comment by NET-OF-BEING** [comment]
maybe i should do a fresh install

**Comment by NET-OF-BEING** [comment]
sudo python3 basicRAT_client.py
Password:
Traceback (most recent call last):
  File "basicRAT_client.py", line 15, in <module>
    from core import crypto, persistence, scan, survey, toolkit
  File "/Users/derekchan/GitHub/basicRAT/basicRAT/core/crypto.py", line 11, in <module>
    from Crypto import Random
ModuleNotFoundError: No module named 'Crypto'

**Comment by NET-OF-BEING** [comment]
should Crypto be references with a Capital C?

**Comment by vesche** [comment]
Yes, it should be capital C. I think a fresh install of Python is what you need. It isn't looking for libraries in the correct paths.

**Comment by NET-OF-BEING** [comment]
okay

**Comment by deadPix3l** [comment]
I would like to point out that `pip install XXXX` and `sudo pip install XXX` MAY (not always, depends on your setup) install the libraries in different locations.

If you are running sudo on the pip install, then you should sudo when you run the server. or neither for both, but consistency is key. or else `sudo pip` will install the libraries in a root/systemwide folder, and python will look for your user specific locations and not find them.
